/**
 * seed-sheets.ts — CP4.3's fixture content for the `sheet-editor` canvas scene.
 *
 * `initialSpreadsheetDocument()` (called by `document-detail.tsx` itself,
 * unmodified) produces a genuinely empty sheet: one tab, zero cells. That is
 * a legitimate state to design against, but not a useful one to LOOK at, so
 * this seeds a small "Q4 Revenue Model" — real values AND real formulas
 * (including cross-references), because a design review of the sheets
 * engine needs to see both the value renderer and the formula bar/dependency
 * highlight, not just static text.
 *
 * Cell addressing uses `toSref` from `@wafflebase/sheets` (the same function
 * `MemStore`/`YorkieStore` use internally) rather than hand-writing "A1"
 * strings. `toSref` is `toColumnLabel(c) + r` and BOTH axes are 1-BASED:
 * `toSref({r:1,c:1}) === "A1"`. Row/column 0 are not "the first" — they are
 * INVALID: `toColumnLabel(0)` is the empty string, so `toSref({r:0,c:0})`
 * yields the bare sref `"0"`, which `parseRef` rejects outright with
 * "Invalid Reference". (An earlier draft of this file used 0-based `r`/`c`
 * and asserted the opposite in this very comment; the whole first column
 * would have been written under the un-parseable keys "1".."6".)
 *
 * VALUES ARE NOT HAND-COMPUTED. Every `v` below was produced by driving the
 * real engine — `new Sheet(new MemStore())` + `setData()` per cell, exactly
 * as typing into the grid does — and reading back what it persisted. Two
 * things that matters for:
 *
 *  1. A formula cell MUST carry its computed `v`. `toDisplayString()` starts
 *     `if (!cell || !cell.v) return ''`, and `calculate()` is only ever
 *     reached from mutation paths (`setData`, `moveCells`, `sortFilterBy…`)
 *     — nothing recalculates on load. Seeding `f` alone renders BLANK, which
 *     would have silently emptied the Profit column and the whole Total row.
 *  2. `f` is stored WITH its leading `=` (`"=B3-C3"`). That is what `setData`
 *     persists, so it is what a real document contains.
 *
 * Both are the same rule the rest of this package follows: the fixture holds
 * what production would have written, so the sandbox paints what production
 * paints. `scripts/smoke-canvas.ts` re-derives these values from the engine
 * and fails if they drift.
 *
 * Exported as a plain function and imported DIRECTLY by `yorkie-offline.tsx`
 * (never the other way around, and never via a relative import FROM this
 * file back to `yorkie-offline.tsx`) — see that file's own `CANVAS_SEEDS`
 * comment for why: a relative import of `yorkie-offline` from here would
 * resolve through `scenePatch()`'s default frame-query propagation instead
 * of the `yorkieOffline()` plugin's unconditional redirect, landing on a
 * SEPARATE module instance from the one `DocumentProvider` reads — a
 * registry entry set in one Map, read from another, silently never found.
 */
import { toSref } from "@wafflebase/sheets";
import type { Document } from "@yorkie-js/sdk";

/**
 * `v` is always present — a formula cell carries BOTH its formula and the
 * value the engine computed for it, which is what `setData` persists (see the
 * header). Modelled as a required field rather than `v?:` so a value-less
 * formula cell is not representable.
 */
interface SeedCell {
  r: number;
  c: number;
  v: string;
  f?: string;
}

/** Generated by driving the real engine; see `scripts/smoke-canvas.ts`. */
const CELLS: SeedCell[] = [
  { r: 1, c: 1, v: "Q4 Revenue Model" },

  { r: 2, c: 1, v: "Month" },
  { r: 2, c: 2, v: "Revenue" },
  { r: 2, c: 3, v: "Costs" },
  { r: 2, c: 4, v: "Profit" },

  { r: 3, c: 1, v: "October" },
  { r: 3, c: 2, v: "182400" },
  { r: 3, c: 3, v: "134200" },
  { r: 3, c: 4, v: "48200", f: "=B3-C3" },

  { r: 4, c: 1, v: "November" },
  { r: 4, c: 2, v: "196800" },
  { r: 4, c: 3, v: "141500" },
  { r: 4, c: 4, v: "55300", f: "=B4-C4" },

  { r: 5, c: 1, v: "December" },
  { r: 5, c: 2, v: "241100" },
  { r: 5, c: 3, v: "158900" },
  { r: 5, c: 4, v: "82200", f: "=B5-C5" },

  { r: 6, c: 1, v: "Total" },
  { r: 6, c: 2, v: "620300", f: "=SUM(B3:B5)" },
  { r: 6, c: 3, v: "434600", f: "=SUM(C3:C5)" },
  { r: 6, c: 4, v: "185700", f: "=SUM(D3:D5)" },
];

/** Registered under docKey `sheet-fixture` in `yorkie-offline.tsx#CANVAS_SEEDS`. */
export function seedSheetsFixture(doc: Document<never, never>): void {
  doc.update((root) => {
    const sheets = (
      root as unknown as { sheets?: Record<string, { cells: Record<string, unknown> }> }
    ).sheets;
    if (!sheets) return;
    // `initialSpreadsheetDocument()` always names its one tab `DEFAULT_TAB_ID`
    // (`tab-1`); this seeder only ever runs on a freshly constructed fixture
    // document, so the first (only) tab is always the one to fill.
    const tabId = Object.keys(sheets)[0];
    if (!tabId) return;
    const cells = sheets[tabId].cells;
    for (const cell of CELLS) {
      // Mirrors the engine's own storage shape: `{ v }` for a literal,
      // `{ v, f }` for a formula — never `{ f }` alone (see the header).
      cells[toSref({ r: cell.r, c: cell.c })] = cell.f
        ? { v: cell.v, f: cell.f }
        : { v: cell.v };
    }
  });
}
