import { parseRef } from '../core/coordinates';
import type { Range, Ref, SelectionType } from '../core/types';
import type { RangeStylePatch } from '../worksheet/range-styles';
import type { UndoSelection } from '../../store/store';
import { parseWorksheetCellKey } from './worksheet-record';

/**
 * `UndoOperation` is the shape of one CRDT operation replayed by an undo or
 * redo, as reported by the collaboration layer.
 *
 * Structural rather than imported so this module — and its tests — stay free
 * of the Yorkie SDK. `@yorkie-js/sdk`'s `OperationInfo` union satisfies it.
 */
export type UndoOperation = {
  type: string;
  path: string;
  key?: string;
};

/**
 * `UndoTabSnapshot` is the part of a worksheet that an undo can change
 * *without* the operation saying where: array operations carry no index and
 * no value, so the affected span is recovered by diffing the array either
 * side of the replay.
 */
export type UndoTabSnapshot = {
  rowOrder: ReadonlyArray<string>;
  colOrder: ReadonlyArray<string>;
  rangeStyles: ReadonlyArray<RangeStylePatch>;
};

/** Paths reach a worksheet as `$.sheets.<tabId>[.<rest>]`. */
const SheetPathPrefix = '$.sheets.';

/**
 * What one tab's share of an undo's operations touched. Kept as coordinates
 * rather than a range so the caller can tell a whole-row change from a cell
 * one — `rowHeights` names rows, `cells` names cells, and they select
 * differently.
 */
type TabTouch = {
  tabId: string;
  cells: Array<Ref>;
  rows: Set<number>;
  columns: Set<number>;
  /** A `rowOrder` / `colOrder` operation: rows or columns were inserted or deleted. */
  rowAxis: boolean;
  colAxis: boolean;
  /** A `rangeStyles` operation, whose range is recovered by diffing. */
  rangeStyles: boolean;
  /** Operations reaching this tab at all, used to pick between tabs. */
  weight: number;
};

function emptyTouch(tabId: string): TabTouch {
  return {
    tabId,
    cells: [],
    rows: new Set(),
    columns: new Set(),
    rowAxis: false,
    colAxis: false,
    rangeStyles: false,
    weight: 0,
  };
}

/**
 * Splits `$.sheets.<tabId>.cells.r3|c2` into its tab id and the remainder
 * below it. Tab ids are generated by `generateTabId` as `tab-<ts>-<alnum>`
 * and cell keys join two axis ids with `|`, so neither contains a `.` and
 * splitting on it is unambiguous.
 */
function parseSheetPath(
  path: string,
): { tabId: string; rest: string } | undefined {
  if (!path.startsWith(SheetPathPrefix)) return undefined;
  const tail = path.slice(SheetPathPrefix.length);
  if (!tail) return undefined;
  const pivot = tail.indexOf('.');
  return pivot === -1
    ? { tabId: tail, rest: '' }
    : { tabId: tail.slice(0, pivot), rest: tail.slice(pivot + 1) };
}

/** A positive 1-based axis index, or undefined for anything else. */
function parseAxisIndex(key: string | undefined): number | undefined {
  if (key === undefined) return undefined;
  if (!/^\d+$/.test(key)) return undefined;
  const index = Number(key);
  return index >= 1 ? index : undefined;
}

/**
 * Axis id to 1-based index. Built once per snapshot: a bulk step can replay
 * tens of thousands of cell operations, and scanning the axis for each one
 * would make an undo quadratic in the grid.
 */
type AxisLookup = { rows: Map<string, number>; columns: Map<string, number> };

function axisLookup(snapshot: UndoTabSnapshot): AxisLookup {
  const rows = new Map<string, number>();
  snapshot.rowOrder.forEach((id, i) => rows.set(id, i + 1));
  const columns = new Map<string, number>();
  snapshot.colOrder.forEach((id, i) => columns.set(id, i + 1));
  return { rows, columns };
}

function resolveCellKey(
  cellKey: string,
  lookup: AxisLookup,
): Ref | undefined {
  const { rowId, colId } = parseWorksheetCellKey(cellKey);
  if (!rowId || !colId) return undefined;
  const r = lookup.rows.get(rowId);
  const c = lookup.columns.get(colId);
  // A cell whose row or column no longer exists — undoing a row insert
  // removes both — has no coordinates to point at.
  if (r === undefined || c === undefined) return undefined;
  return { r, c };
}

/** Memoises {@link axisLookup} per tab across one replay's operations. */
function lookupCache(
  snapshots: ReadonlyMap<string, UndoTabSnapshot>,
): (tabId: string) => AxisLookup | undefined {
  const cache = new Map<string, AxisLookup | undefined>();
  return (tabId) => {
    if (!cache.has(tabId)) {
      const snapshot = snapshots.get(tabId);
      cache.set(tabId, snapshot ? axisLookup(snapshot) : undefined);
    }
    return cache.get(tabId);
  };
}

/**
 * Buckets an undo's operations by tab, resolving cell keys against the
 * post-replay axes — which is where the selection is going to land.
 *
 * Falling back to the pre-replay axes covers the step that undoes a write
 * into untouched space: the axis grew to reach the cell, so undoing it takes
 * those ids away again and the cell the user is being shown has no
 * post-replay coordinates. The truncation is at the tail (a structural
 * delete is handled by the axis branch instead), so indices below it mean
 * the same thing either side.
 */
function collectTouches(
  ops: ReadonlyArray<UndoOperation>,
  before: ReadonlyMap<string, UndoTabSnapshot>,
  after: ReadonlyMap<string, UndoTabSnapshot>,
): Map<string, TabTouch> {
  const touches = new Map<string, TabTouch>();
  const afterLookup = lookupCache(after);
  const beforeLookup = lookupCache(before);

  for (const op of ops) {
    const parsed = parseSheetPath(op.path);
    if (!parsed) continue;
    const lookup = afterLookup(parsed.tabId);
    if (!lookup) continue;
    const fallback = beforeLookup(parsed.tabId);

    let touch = touches.get(parsed.tabId);
    if (!touch) {
      touch = emptyTouch(parsed.tabId);
      touches.set(parsed.tabId, touch);
    }
    touch.weight += 1;

    // `$.sheets.<tab>.cells` with the cell key, or `…cells.<cellKey>` with a
    // field key when a single field of an existing cell was written.
    const cellKey =
      parsed.rest === 'cells'
        ? op.key
        : parsed.rest.startsWith('cells.')
          ? parsed.rest.slice('cells.'.length)
          : undefined;
    if (cellKey) {
      const ref =
        resolveCellKey(cellKey, lookup) ??
        (fallback ? resolveCellKey(cellKey, fallback) : undefined);
      if (ref) touch.cells.push(ref);
      continue;
    }

    switch (parsed.rest) {
      case 'rowOrder':
        touch.rowAxis = true;
        break;
      case 'colOrder':
        touch.colAxis = true;
        break;
      case 'rangeStyles':
        touch.rangeStyles = true;
        break;
      case 'merges': {
        if (!op.key) break;
        try {
          touch.cells.push(parseRef(op.key));
        } catch {
          // A merge key the engine cannot parse points nowhere.
        }
        break;
      }
      case 'rowHeights':
      case 'rowStyles': {
        const index = parseAxisIndex(op.key);
        if (index) touch.rows.add(index);
        break;
      }
      case 'colWidths':
      case 'colStyles': {
        const index = parseAxisIndex(op.key);
        if (index) touch.columns.add(index);
        break;
      }
      case '':
        // A field written as a whole value rather than mutated in place
        // reports as a `set` on the worksheet itself, with the field in
        // `key`. `rangeStyles` is the one that matters: `setRangeStyles`
        // assigns (or deletes) the entire array, and that is the path every
        // style *merge, compaction and replace* takes — `addRangeStyle`'s
        // array push is the rarer one. Matching only the push left the
        // selection put for most style undos, which is the row this whole
        // resolver exists to fix.
        if (op.key === 'rangeStyles') touch.rangeStyles = true;
        break;
      default:
        // Freeze pane, filter state, hidden rows, charts, comments: the tab
        // is known but the change has no coordinates. `weight` still counts
        // it, so a tab touched only this way can still win the tab choice
        // and produce a jump without a selection.
        break;
    }
  }

  return touches;
}

/**
 * What one tab's share of a replay amounts to. A step reaches several tabs
 * more often than it looks: `shiftCrossTabDataRanges` rewrites every other
 * tab's chart and pivot source ranges inside the same change as the row
 * insert that moved them.
 */
const enum TabRank {
  /** Touched, but with nothing to point at — a chart range, a freeze pane. */
  Incidental = 0,
  /** Yields a range: cells, a resized axis, a style region. */
  Coordinates = 1,
  /** Rows or columns were inserted, deleted or reordered here. */
  Structural = 2,
}

/** One tab's resolved answer, before choosing between tabs. */
type Candidate = {
  tabId: string;
  rank: TabRank;
  weight: number;
  selectionType: SelectionType;
  range?: Range;
};

/**
 * Picks the tab whose selection should be restored.
 *
 * Ranked by what each tab *carries*, not by which one happens to be open. A
 * structural edit is the cause and the chart ranges it rewrote elsewhere are
 * its effects, so the tab holding the axis change wins even when the user is
 * sitting on one of the tabs that merely received a side effect — otherwise
 * undo lands on a tab with no coordinates to show and appears to do nothing,
 * which is the whole failure this resolver exists to remove.
 *
 * The open tab is preferred only *within* a rank, which is where the original
 * reasoning still holds: between two tabs that both changed substantively,
 * undo should not send you away from the one you are working in.
 */
function pickCandidate(
  candidates: ReadonlyArray<Candidate>,
  currentTabId: string,
): Candidate | undefined {
  let topRank = TabRank.Incidental;
  for (const candidate of candidates) {
    if (candidate.rank > topRank) topRank = candidate.rank;
  }

  let best: Candidate | undefined;
  for (const candidate of candidates) {
    if (candidate.rank !== topRank) continue;
    if (candidate.tabId === currentTabId) return candidate;
    if (!best || candidate.weight > best.weight) best = candidate;
  }
  return best;
}

/**
 * The first and last index at which two axis id arrays disagree, which for an
 * insert or a delete is exactly the affected span. Returns undefined when
 * they are identical, or when the axis only grew or shrank at its **end**.
 *
 * That last case is not a structural edit at all: writing a cell into
 * untouched space grows `rowOrder` / `colOrder` to reach it in the same
 * change, so every ordinary cell write carries an axis operation too. Both
 * are told apart by where they land — an insert or a delete disturbs the
 * middle, extent growth only appends. Selecting the appended rows instead of
 * the cell that caused them is how the first cut of this got the common case
 * wrong.
 */
function diffAxisSpan(
  before: ReadonlyArray<string>,
  after: ReadonlyArray<string>,
): { from: number; to: number } | undefined {
  const shorter = Math.min(before.length, after.length);
  let head = 0;
  while (head < shorter && before[head] === after[head]) head++;

  // The shorter array is a prefix of the longer: identical, or a pure
  // append/truncate at the tail.
  if (head === shorter) return undefined;

  let tail = 0;
  while (
    tail < shorter - head &&
    before[before.length - 1 - tail] === after[after.length - 1 - tail]
  ) {
    tail++;
  }

  const changed = after.length - head - tail;
  // A delete leaves nothing to select at `head`; point at the row or column
  // that closed the gap, clamped into the axis.
  const from = head + 1;
  const to = changed > 0 ? head + changed : from;
  return { from, to: Math.max(from, to) };
}

/**
 * The range of every `rangeStyles` patch the replay added or removed. Style
 * operations carry neither index nor value, so the patch list is diffed
 * instead — it holds one entry per compacted style region, so this is a
 * short list.
 *
 * The difference is taken in **both** directions and unioned. Styling a range
 * usually replaces one patch with another rather than adding one, and taking
 * only the additions would then report the new region while leaving out
 * whatever the old one covered beyond it.
 */
function diffRangeStyles(
  before: ReadonlyArray<RangeStylePatch>,
  after: ReadonlyArray<RangeStylePatch>,
): Range | undefined {
  // A multiset, so a patch list that merely gained a duplicate still counts as
  // changed.
  const tally = (patches: ReadonlyArray<RangeStylePatch>) => {
    const counts = new Map<string, { patch: RangeStylePatch; count: number }>();
    for (const patch of patches) {
      const key = JSON.stringify(patch);
      const entry = counts.get(key);
      if (entry) entry.count += 1;
      else counts.set(key, { patch, count: 1 });
    }
    return counts;
  };

  const beforeTally = tally(before);
  const afterTally = tally(after);

  const changed: Array<RangeStylePatch> = [];
  for (const key of new Set([...beforeTally.keys(), ...afterTally.keys()])) {
    const wasThere = beforeTally.get(key);
    const isThere = afterTally.get(key);
    if ((wasThere?.count ?? 0) === (isThere?.count ?? 0)) continue;
    // Either side's copy carries the same range; take whichever exists.
    changed.push((isThere ?? wasThere)!.patch);
  }
  if (changed.length === 0) return undefined;

  return boundingRange(changed.flatMap((patch) => patch.range));
}

/**
 * Smallest and largest of a set, by iteration rather than by spreading it
 * into `Math.min` — "resize every row" puts one entry per row in here.
 */
function extent(values: ReadonlySet<number>): { min: number; max: number } {
  let min = Infinity;
  let max = -Infinity;
  for (const value of values) {
    if (value < min) min = value;
    if (value > max) max = value;
  }
  return { min, max };
}

function boundingRange(refs: ReadonlyArray<Ref>): Range | undefined {
  if (refs.length === 0) return undefined;
  let minR = Infinity;
  let maxR = -Infinity;
  let minC = Infinity;
  let maxC = -Infinity;
  for (const ref of refs) {
    if (ref.r < minR) minR = ref.r;
    if (ref.r > maxR) maxR = ref.r;
    if (ref.c < minC) minC = ref.c;
    if (ref.c > maxC) maxC = ref.c;
  }
  return [
    { r: minR, c: minC },
    { r: maxR, c: maxC },
  ];
}

/**
 * Resolves one tab's share of a replay into the selection it would restore.
 * Ranked so {@link pickCandidate} can tell the tab that was edited from the
 * tabs that only absorbed a side effect.
 */
function resolveTab(
  touch: TabTouch,
  before: ReadonlyMap<string, UndoTabSnapshot>,
  after: ReadonlyMap<string, UndoTabSnapshot>,
): Candidate | undefined {
  const snapshotBefore = before.get(touch.tabId);
  const snapshotAfter = after.get(touch.tabId);
  if (!snapshotAfter) return undefined;

  const base = { tabId: touch.tabId, weight: touch.weight };

  // A structural step is about the rows or columns themselves, so select
  // their headers the way Google Sheets does — not the cells that moved.
  // `diffAxisSpan` answers `undefined` for a tail-only change, which is the
  // axis growing to reach a cell rather than an insert or a delete; those
  // fall through to the cell branch below.
  const rowSpan =
    touch.rowAxis && snapshotBefore
      ? diffAxisSpan(snapshotBefore.rowOrder, snapshotAfter.rowOrder)
      : undefined;
  const colSpan =
    touch.colAxis && snapshotBefore
      ? diffAxisSpan(snapshotBefore.colOrder, snapshotAfter.colOrder)
      : undefined;

  if (rowSpan) {
    return {
      ...base,
      rank: TabRank.Structural,
      selectionType: 'row',
      range: [
        { r: rowSpan.from, c: 1 },
        { r: rowSpan.to, c: Math.max(1, snapshotAfter.colOrder.length) },
      ],
    };
  }
  if (colSpan) {
    return {
      ...base,
      rank: TabRank.Structural,
      selectionType: 'column',
      range: [
        { r: 1, c: colSpan.from },
        { r: Math.max(1, snapshotAfter.rowOrder.length), c: colSpan.to },
      ],
    };
  }

  const cellRange = boundingRange(touch.cells);
  if (cellRange) {
    return {
      ...base,
      rank: TabRank.Coordinates,
      selectionType: 'cell',
      range: cellRange,
    };
  }

  // Resizing or restyling whole rows or columns selects those headers.
  if (touch.rows.size > 0 && touch.columns.size === 0) {
    const rows = extent(touch.rows);
    return {
      ...base,
      rank: TabRank.Coordinates,
      selectionType: 'row',
      range: [
        { r: rows.min, c: 1 },
        { r: rows.max, c: Math.max(1, snapshotAfter.colOrder.length) },
      ],
    };
  }
  if (touch.columns.size > 0 && touch.rows.size === 0) {
    const columns = extent(touch.columns);
    return {
      ...base,
      rank: TabRank.Coordinates,
      selectionType: 'column',
      range: [
        { r: 1, c: columns.min },
        { r: Math.max(1, snapshotAfter.rowOrder.length), c: columns.max },
      ],
    };
  }
  // Both axes carry metadata (a step that resized rows *and* columns, or
  // restyled both). Neither header selection describes it, so fall back to
  // the block they bound rather than reporting nothing.
  if (touch.rows.size > 0 && touch.columns.size > 0) {
    const rows = extent(touch.rows);
    const columns = extent(touch.columns);
    return {
      ...base,
      rank: TabRank.Coordinates,
      selectionType: 'cell',
      range: [
        { r: rows.min, c: columns.min },
        { r: rows.max, c: columns.max },
      ],
    };
  }

  if (touch.rangeStyles && snapshotBefore) {
    const range = diffRangeStyles(
      snapshotBefore.rangeStyles,
      snapshotAfter.rangeStyles,
    );
    if (range) {
      return {
        ...base,
        rank: TabRank.Coordinates,
        selectionType: 'cell',
        range,
      };
    }
  }

  // The tab is known but the step has no coordinates here (a freeze pane, a
  // filter, a chart range rewritten by somebody else's row insert). Worth
  // naming as a fallback, not worth moving the cursor for.
  return { ...base, rank: TabRank.Incidental, selectionType: 'cell' };
}

/**
 * `resolveUndoSelection` turns the operations an undo or redo replayed into
 * the selection that should be restored.
 *
 * Reading the operations is what makes this exact where diffing document
 * state is not: a cell overwritten with a new value leaves the key set
 * untouched, and a style or a column width never appears in it at all.
 *
 * `before` and `after` supply the two array fields whose operations say
 * neither where nor what — the axis orders and the range styles.
 */
export function resolveUndoSelection(
  ops: ReadonlyArray<UndoOperation>,
  before: ReadonlyMap<string, UndoTabSnapshot>,
  after: ReadonlyMap<string, UndoTabSnapshot>,
  currentTabId: string,
): UndoSelection | undefined {
  const candidates: Array<Candidate> = [];
  for (const touch of collectTouches(ops, before, after).values()) {
    const candidate = resolveTab(touch, before, after);
    if (candidate) candidates.push(candidate);
  }

  const best = pickCandidate(candidates, currentTabId);
  if (!best) return undefined;

  return {
    tabId: best.tabId,
    otherTab: best.tabId !== currentTabId,
    selectionType: best.selectionType,
    range: best.range,
  };
}
