/**
 * `virtual:wb-scenes` — generated by the plugin at serve time, so there is no file for
 * `tsc` to read. Only the members this package uses are declared; the frame entry inside
 * `@wafflebase/design-editor` has its own view of the same module.
 */
declare module 'virtual:wb-scenes' {
  export const scenes: { id: string; route?: string; file: string; label: string }[];
  export const hasProviders: boolean;
}
