import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { palette } from '../src/tokens/palette';
import { semantic } from '../src/tokens/semantic';
import { radius } from '../src/tokens/radius';
import { typography } from '../src/tokens/typography';

// Map of CSS variable name -> value, in deterministic emission order.
type Block = Array<[string, string]>;

/**
 * The four token sources this generator reads.
 *
 * Parameterized so the design-editor bridge can render `tokens.css` from PATCHED
 * sources without writing them to disk — that is how a staged token edit
 * previews on `--wb-*` consumers and in the canvas engines
 * (`POST /__design-editor/preview-tokens`). The alternative was porting the
 * mode-conditional logic below into the sandbox client, which would make the
 * preview's colour maths a second implementation of this emitter, free to drift.
 *
 * `renderTokensCss()` keeps the module's own imports as the sources, so the CLI
 * path and every existing caller are byte-for-byte unchanged.
 */
export interface TokenSources {
  palette: typeof palette;
  semantic: typeof semantic;
  radius: typeof radius;
  typography: typeof typography;
}

function paletteBlock(src: TokenSources, mode: 'light' | 'dark'): Block {
  const { palette } = src;
  const n = mode === 'light' ? palette.neutrals.light : palette.neutrals.dark;
  const syrupForMode = mode === 'light' ? palette.syrup : palette.syrupBright;
  const berryForMode = mode === 'light' ? palette.berry : palette.berryBright;
  const leafForMode = mode === 'light' ? palette.leaf : palette.leafBright;
  return [
    ['--wb-bg', n.bg],
    ['--wb-paper', n.paper],
    ['--wb-ink', n.ink],
    ['--wb-sub', n.sub],
    ['--wb-rule', n.rule],
    ['--wb-syrup', syrupForMode],
    ['--wb-syrup-deep', mode === 'light' ? palette.syrupDeep : palette.butter],
    ['--wb-butter', palette.butter],
    ['--wb-berry', berryForMode],
    ['--wb-leaf', leafForMode],
  ];
}

function semanticBlock(src: TokenSources, mode: 'light' | 'dark'): Block {
  const m = src.semantic[mode];
  return [
    ['--background', m.background],
    ['--foreground', m.foreground],
    ['--card', m.card],
    ['--card-foreground', m.cardForeground],
    ['--popover', m.popover],
    ['--popover-foreground', m.popoverForeground],
    ['--primary', m.primary],
    ['--primary-foreground', m.primaryForeground],
    ['--secondary', m.secondary],
    ['--secondary-foreground', m.secondaryForeground],
    ['--muted', m.muted],
    ['--muted-foreground', m.mutedForeground],
    ['--accent', m.accent],
    ['--accent-foreground', m.accentForeground],
    ['--destructive', m.destructive],
    ['--border', m.border],
    ['--input', m.input],
    ['--ring', m.ring],
    ['--chart-1', m.chart1],
    ['--chart-2', m.chart2],
    ['--chart-3', m.chart3],
    ['--chart-4', m.chart4],
    ['--chart-5', m.chart5],
    ['--sidebar', m.sidebar],
    ['--sidebar-foreground', m.sidebarForeground],
    ['--sidebar-primary', m.sidebarPrimary],
    ['--sidebar-primary-foreground', m.sidebarPrimaryForeground],
    ['--sidebar-accent', m.sidebarAccent],
    ['--sidebar-accent-foreground', m.sidebarAccentForeground],
    ['--sidebar-border', m.sidebarBorder],
    ['--sidebar-ring', m.sidebarRing],
  ];
}

function rootOnlyBlock(src: TokenSources): Block {
  return [
    ['--radius', src.radius.base],
    // Terminal palette is locked across both modes (matches existing index.css).
    ['--wb-terminal-bg', src.palette.terminal.bg],
    ['--wb-terminal-fg', src.palette.terminal.fg],
    // Font families — listed once, do not change between modes.
    ['--font-display', src.typography.display],
    ['--font-body', src.typography.body],
    ['--font-code', src.typography.code],
  ];
}

function format(block: Block, selector: string): string {
  const lines = block.map(([k, v]) => `  ${k}: ${v};`).join('\n');
  return `${selector} {\n${lines}\n}`;
}

/** The `:root` / `.dark` variable blocks, as ordered `[name, value]` pairs. */
export function tokenBlocks(src: TokenSources): { light: Block; dark: Block } {
  return {
    light: [...rootOnlyBlock(src), ...paletteBlock(src, 'light'), ...semanticBlock(src, 'light')],
    dark: [...paletteBlock(src, 'dark'), ...semanticBlock(src, 'dark')],
  };
}

/** Render `tokens.css` from explicit sources (used by the design-editor preview). */
export function renderTokensCssFrom(src: TokenSources): string {
  const { light, dark } = tokenBlocks(src);
  return [
    '/* AUTOGENERATED by packages/core/scripts/build-css.ts — do not edit. */',
    format(light, ':root'),
    format(dark, '.dark'),
    '',
  ].join('\n\n');
}

export function renderTokensCss(): string {
  return renderTokensCssFrom({ palette, semantic, radius, typography });
}

const isMain = process.argv[1] === fileURLToPath(import.meta.url);
if (isMain) {
  const outPath = resolve(dirname(fileURLToPath(import.meta.url)), '../dist/tokens.css');
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, renderTokensCss(), 'utf8');
  console.log(`wrote ${outPath}`);
}
