/**
 * The scene frame's boot, served by the CONSUMER's dev server.
 *
 * NOT PART OF THE SHELL BUNDLE, and that is the design. `index.html` is prebuilt with
 * our React so the consumer's Tailwind cannot restyle our chrome; this file is the
 * inverse — it renders THEIR components, imports `virtual:wb-scenes`, and needs their
 * `plugin-react`. So it stays source, and `shellServer` points `scene.html` at it.
 * 11a proved that serve path with a React-free placeholder; this is the mount.
 *
 * ONLY THE ENVIRONMENTAL PARTS ARE HERE. Every decision the frame makes — which export
 * to mount, which `wb:error` kind a failure is, whether providers wrap — lives in
 * `scene-frame.tsx`, because this module imports a virtual id that does not exist on
 * disk and therefore cannot be imported by a test without bundler aliasing.
 *
 * WHICH REACT THIS RESOLVES, measured rather than assumed. 11a recorded a risk that
 * `react` imported from inside our own package would find OUR copy — a devDependency
 * the shell build needs — and that two Reacts here would break hooks in the components
 * under review. Against a live Vite 6.4.3 with two marked React copies: the dep
 * optimizer pre-bundles `react` ONCE from the project root, and both this entry and the
 * consumer's own components import that single chunk; our copy appears nowhere in
 * `.vite/deps`. No `resolve.dedupe` and no peer dependency are needed.
 *
 * NO STYLESHEET IMPORT. The prototype opened with `import './sandbox.css'`, the same
 * specifier its shell used, so the frame inherited the editor's stylesheet. §6 is
 * explicit that the frame keeps using the HOST's: the scene is the thing under review,
 * and dressing it in our CSS would be measuring the instrument.
 *
 * NO `StrictMode`. Its double-invoke tests mount/unmount correctness; this frame is a
 * surface for judging what the app PAINTS, and doubling would double-fire fixture
 * requests and double-mount whatever engines a scene holds.
 */
import { createRoot } from 'react-dom/client';
// @ts-expect-error -- generated by the plugin at serve time; there is no file to type.
import { loadScene, loadComponentFile, hasProviders, scenes, fixturesFor } from 'virtual:wb-scenes';
import { emptyFixtureTable, installFetchGuard } from './fetch-fixtures.ts';
import { installPicker, renderedClasses, selectableIds } from './frame-picker.ts';
import { ComponentFrame } from './ComponentFrame.tsx';
import { installViewGestures } from './view-gestures.ts';
import type { IconSlot } from './preview-icons.tsx';
import { installHmrStatePreservation } from './hmr-state.ts';
import { SceneFrame, type SceneConfigLike } from './scene-frame.tsx';
import { DebugReportSlot } from './debug-report.tsx';
import type { FrameMessage, FrameSide } from './frame-protocol.ts';
import { parseAxes } from './frame-protocol.ts';

/** The four values `sceneFrameUrl` puts on the query string. */
const params = new URLSearchParams(window.location.search);
const sceneId = params.get('scene') ?? '';
const side: FrameSide = params.get('frame') === 'before' ? 'before' : 'after';
const theme: 'light' | 'dark' = params.get('theme') === 'dark' ? 'dark' : 'light';
/**
 * The Mock Data toggle. Read once at load, like the other three: flipping it mid-session
 * would need every already-fired query to refetch, so the host reloads the frame
 * instead — which is why `SceneHost` bakes it into the iframe's `key`.
 */
const mockDataEmpty = params.get('empty') === '1';
/*
 * COMPONENT MODE. Same document, same guard, same providers — only the thing mounted
 * differs, which is why this is a branch here rather than a second HTML entry.
 */
const componentName = params.get('component');
const componentFile = params.get('file');
const componentAxes = parseAxes(params.get('axes'));
const componentForced = params.get('forced') ?? undefined;
const componentLabel = params.get('label') ?? undefined;
/** Malformed JSON degrades to no mocks — the component then reports its own throw. */
const componentProps = (() => {
  try {
    return JSON.parse(params.get('props') ?? '{}') as Record<string, unknown>;
  } catch {
    return {};
  }
})();
const componentNoops = (params.get('noops') ?? '').split(',').filter(Boolean);
const componentIconSlot = (params.get('iconSlot') ?? 'none') as IconSlot;
const componentIcon = params.get('icon') ?? 'plus';

/** One-way channel to the host. Origin-pinned; see `frame-protocol.ts`. */
function send(msg: FrameMessage): void {
  try {
    window.parent.postMessage(msg, window.location.origin);
  } catch {
    /* the host went away mid-teardown */
  }
}

const config = (scenes as SceneConfigLike[]).find((s) => s.id === sceneId);

/**
 * Paint the theme class before React mounts, so a frame reload does not flash light.
 *
 * `.dark` is hardcoded and that is a recorded gap: 10b made `applyTokenVars`' dark
 * selector a parameter and nothing configures it yet. A project whose dark selector is
 * `[data-theme="dark"]` gets no pre-paint — a flash, not a wrong render.
 */
if (theme === 'dark') document.documentElement.classList.add('dark');

/*
 * A COMPONENT PREVIEW HAS NO GROUND OF ITS OWN.
 *
 * The consumer's stylesheet paints `body`, which is right for a page and wrong here:
 * the host draws a grid on the container this frame moves across, and an opaque body
 * covers it with a rectangle that travels with the frame. Clearing it on the DOCUMENT
 * is what lets the grid show through; the iframe element's own background is cleared
 * on the host side.
 */
if (params.get('component')) {
  document.documentElement.style.background = 'transparent';
  document.body.style.background = 'transparent';
  // Full height, so `align-items: center` has a box to centre within — otherwise the
  // grid shrink-wraps its one child and the component sits at the top.
  document.documentElement.style.height = '100%';
  document.body.style.height = '100%';
  /*
   * THE MOUNT NODE TOO, and this is the one that was missing.
   *
   * `html` and `body` being full size is not enough: the grid centres within its own
   * parent, and `#wb-scene-root` sizes to its content by default — so the flex box was
   * as wide as the button inside it and "centre" centred nothing. The component sat at
   * the left edge, vertically centred, which is exactly what a full-height,
   * content-width parent produces.
   */
  const mount = document.getElementById('wb-scene-root');
  if (mount) {
    mount.style.height = '100%';
    mount.style.width = '100%';
  }
  installViewGestures(send);
}

/**
 * FIXTURES COME FROM THE CONSUMER, resolved by their own module.
 *
 * The manifest's `mocks` / `fixtures` / `shell` fields name what a scene needs; turning
 * `"documents/list"` into data is the consumer's job, because the data is theirs. The
 * plugin's `fixtures` option supplies the resolver and `virtual:wb-scenes` re-exports it,
 * defaulting to one that returns `{}`.
 *
 * 11b READ THE WRONG FIELD. It passed `config.mocks` — a string ARRAY documenting the
 * scene's dependency surface — as the URL-keyed table, so a real manifest produced keys
 * `"0"`, `"1"`, `"2"`. It went unnoticed because the fixture consumer declares
 * `"mocks": []`, which degrades to an empty table and passes.
 *
 * Installed BEFORE any scene module is imported, which is why this is a static import
 * and not part of `loadScene`'s lazy pair. Real API modules read their base URL at module
 * scope and real pages fire queries on mount, so a guard installed after the import has
 * already lost the race — and an escaped request reaches the consumer's actual backend
 * from inside a frame whose whole premise is that it does not.
 */
/*
 * A COMPONENT PREVIEW GETS THE SHELL'S FIXTURES.
 *
 * `config` is undefined outside a scene, so the table was empty and every app component
 * that fetches — `NavUser` asking `/api/auth/me` — reported an unmocked request and
 * rendered nothing. Asking for the same `shell: 'app'` set a shell-mounted scene gets is
 * what makes those components mountable, and it goes through the CONSUMER's resolver
 * like any other: the editor names the need, the project answers it.
 */
const declared = fixturesFor(
  config ?? (componentName ? ({ id: componentName, shell: 'app', mocks: ['auth'] } as never) : undefined),
);
installFetchGuard({
  fixtures: mockDataEmpty ? emptyFixtureTable(declared) : declared,
  /*
   * TWO KINDS, because they mean opposite things. A missing fetch fixture is a DEFECT: the
   * scene asked for data, got nothing, and is rendering something a user would never see. A
   * refused `EventSource` is the DESIGN: a stream has no fixture shape and no scene reads
   * what it carries, so the guard turns it away on purpose. Reporting both as `fetch` made
   * every shell scene look like it had a fixture gap forever, which is how a real gap hides.
   */
  onMiss: (url, method) =>
    method === 'EVENTSOURCE'
      ? send({ type: 'wb:error', kind: 'stream', message: `refused stream ${url}`, url })
      : send({ type: 'wb:error', kind: 'fetch', message: `unmocked ${method} ${url}`, url }),
});

/**
 * At module scope, not in an effect, so they survive every scene re-render. Both are
 * idempotent, so a fast-refresh update cannot stack a second set of capture listeners
 * and double-report every click.
 */
installPicker({ send });
installHmrStatePreservation();

/**
 * A throw that escapes React — an event handler, a stray promise — would otherwise
 * leave the frame merely blank, which reads as a scene that renders nothing.
 */
window.addEventListener('error', (e) =>
  send({ type: 'wb:error', kind: 'render', message: e.message }),
);
window.addEventListener('unhandledrejection', (e) =>
  send({
    type: 'wb:error',
    kind: 'render',
    message: e.reason instanceof Error ? e.reason.message : String(e.reason),
  }),
);

const root = document.getElementById('wb-scene-root');
if (!root) {
  throw new Error('[design-editor] #wb-scene-root missing from the scene document');
}
createRoot(root).render(
  <>
    {componentName && componentFile ? (
      <ComponentFrame
        file={componentFile}
        component={componentName}
        axes={componentAxes}
        forced={componentForced}
        label={componentLabel}
        mockProps={componentProps}
        noopProps={componentNoops}
        iconSlot={componentIconSlot}
        icon={componentIcon}
        side={side}
        hasProviders={hasProviders}
        theme={theme}
        loadComponentFile={loadComponentFile}
        onReady={() =>
          // `scene` names WHAT the frame is showing, and in this mode that is a component
          // rather than a route. The host keys its state on it either way.
          send({ type: 'wb:ready', scene: componentName, side, selectable: selectableIds() })
        }
        onError={(message) => send({ type: 'wb:error', kind: 'mount', message })}
      />
    ) : (
      <SceneFrame
        sceneId={sceneId}
        side={side}
        theme={theme}
        config={config}
        loadScene={loadScene}
        send={send}
        selectableIds={selectableIds}
        renderedClasses={renderedClasses}
      />
    )}
    {/*
     * A SIBLING of whatever the frame is showing, not a wrapper. The overlay
     * renders nothing until its hotkey is pressed and never takes the pointer,
     * so it cannot change what is painted — and wrapping would put a component
     * of ours inside the tree under review, which is the one thing this frame
     * exists not to do.
     *
     * OUTSIDE THE TERNARY, so a component preview is reportable too: it is a
     * rendered thing a person can see a defect in, and the frame it lives in is
     * this one. `componentName` names it, because for that mode the component IS
     * the route — the same substitution `wb:ready` above makes.
     *
     * EMPTY UNLESS `VITE_WB_DEBUG_REPORT` IS SET: the slot decides, and an
     * unarmed frame never even loads the reporter. `debug-report.tsx` carries
     * the whole argument for why the mount is gated rather than merely idle.
     */}
    <DebugReportSlot
      sceneId={componentName || sceneId}
      side={side}
      theme={theme}
      onLiveChange={(live) => send({ type: 'wb:debug-report', live })}
    />
  </>,
);
