import { extractReferences } from './formula/formula';
import {
  type Grid,
  type Cell,
  type CellStyle,
  type ConditionalFormatOperator,
  type ConditionalFormatRule,
  type ConditionalFormatStyle,
  type DataValidationKind,
  type DataValidationRule,
  type DataValidationOperator,
  type BorderPreset,
  type TextAlign,
  type VerticalAlign,
  type NumberFormat,
  type FilterOperator,
  type FilterCondition,
  type FilterState,
  type HiddenState,
  type AggregateFunction,
  type PivotFieldSort,
  type PivotField,
  type PivotValueField,
  type PivotFilterField,
  type PivotTableDefinition,
  type PivotRecord,
  type GroupNode,
  type PivotCellType,
  type PivotCell,
  type PivotCellFormat,
  type PivotResult,
  type Ref,
  type Sref,
  type Range,
  type Ranges,
  type MergeSpan,
  type Direction,
  type Axis,
  type SelectionType,
  type GridResolver,
} from './model/core/types';
import {
  toColumnLabel,
  parseColumnLabel,
  toSref,
  toSrefs,
  parseRef,
  inRange,
  inRanges,
  isIntersectRanges,
  toRanges,
  toRefsFromRanges,
  toSrngFromRanges,
  parseRanges,
  mergeOverlapping,
  removeRange,
  isCrossSheetRef,
  parseCrossSheetRef,
} from './model/core/coordinates';
import {
  shiftSref,
  shiftFormula,
  shiftDimensionMap,
  shiftColumnLabel,
  shiftA1Range,
  remapIndex,
  moveRef,
  moveFormula,
  moveGrid,
  moveDimensionMap,
  moveColumnLabel,
  moveA1Range,
  relocateFormula,
} from './model/worksheet/shifting';
import {
  cloneConditionalFormatRule,
  moveConditionalFormatRules,
  normalizeConditionalFormatRule,
  normalizeConditionalFormatStyle,
  resolveConditionalFormatStyleAt,
  shiftConditionalFormatRules,
} from './model/worksheet/conditional-format';
import {
  CHECKBOX_TRUE,
  CHECKBOX_FALSE,
  cloneDataValidationRule,
  normalizeDataValidationRule,
  resolveDataValidationAt,
  isCheckboxChecked,
  toggleCheckboxValue,
  listOptionsOf,
  isValidListValue,
  isValidDateValue,
  isValidNumberValue,
  isValidTextValue,
  isValidValueForRule,
  describeDateRule,
  describeNumberRule,
  describeTextRule,
  normalizeListOptions,
  shiftDataValidationRules,
  moveDataValidationRules,
  validationOperandCount,
} from './model/worksheet/data-validation';
import {
  type RangeStylePatch,
  cloneRangeStylePatch,
  normalizeRangeStylePatch,
  mergeStylePatch,
  normalizeStylePatch,
  pruneShadowedRangeStylePatches,
  shiftRangeStylePatches,
  moveRangeStylePatches,
  coalesceAdjacentRangeStylePatches,
  clipRangeStylePatches,
  translateRangeStylePatches,
  resolveRangeStyleAt,
} from './model/worksheet/range-styles';
import {
  toMergeRange,
  isRefInMerge,
  shiftMerge,
  moveMerge,
  shiftMergeMap,
  moveMergeMap,
  isMergeSplitByMove,
} from './model/worksheet/merging';
import { DimensionIndex } from './model/worksheet/dimensions';
import { type Store } from './store/store';
import { MemStore } from './store/memory';
import { CellIndex } from './store/cell-index';
import { findEdgeWithIndex } from './store/find-edge';
import { ReadOnlyStore, toCell } from './store/readonly';
import {
  initialize,
  Spreadsheet,
  type LayoutRect,
  type Theme,
} from './view/spreadsheet';
import { getPeerCursorColor } from './view/theme';
import {
  buildLocaleFormatPreview,
  resolveCurrencyForLocale,
  resolveSystemLocale,
  type LocaleFormatPreview,
} from './model/core/locale';
import {
  formatValue,
  type FormatValueOptions,
} from './model/worksheet/format';
import {
  inferInput,
  defaultAlign,
  type InferInputOptions,
  type InferredInput,
  type InferredInputFormat,
} from './model/worksheet/input';
import {
  getWorksheetCell,
  getWorksheetEntries,
  getWorksheetKeys,
  forEachWorksheetStoredCell,
  writeWorksheetCell,
  updateWorksheetCell,
  replaceWorksheetCells,
  resolveWorksheetCellStyle,
} from './model/workbook/worksheet-grid';
import {
  safeWorksheetRecordKeys,
  safeWorksheetRecordEntries,
  safeWorksheetRecordValues,
  createWorksheetAxisId,
  createWorksheetCellKey,
  parseWorksheetCellKey,
} from './model/workbook/worksheet-record';
import {
  type CellAnchor,
  type RangeAnchor,
  type SelectionPresence,
  anchorToRef,
  refToAnchor,
  rangeAnchorToRange,
  rangeToRangeAnchor,
} from './model/workbook/anchor-conversion';
import { calculatePivot, materialize } from './model/pivot/index';
import { parseSourceData } from './model/pivot/parse';
import { parseRange } from './model/core/coordinates';
import {
  DEFAULT_TAB_ID,
  DEFAULT_TAB_NAME,
  type ChartType,
  type SheetChart,
  type SheetImage,
  type WorksheetFilterState,
  type Worksheet,
  type TabType,
  type SheetKind,
  type TabMeta,
  type SpreadsheetDocument,
  createWorksheet,
  createSpreadsheetDocument,
  initialSpreadsheetDocument,
} from './model/workbook/worksheet-document';
import {
  type Comment,
  type CommentAnchor,
  type CommentAuthor,
  type Thread,
} from './comment/types';
import {
  createThread,
  addReply,
} from './comment/thread';
import { cellAnchorToSref, isAnchorAlive } from './comment/anchor';
import {
  importXlsxFile,
  importXlsxWorkbook,
} from './import/xlsx-importer';
import type { ImportedXlsxSheet, XlsxFileLike } from './import/xlsx-importer';

export {
  initialize,
  Spreadsheet,
  MemStore,
  CellIndex,
  ReadOnlyStore,
  toCell,
  findEdgeWithIndex,
  DimensionIndex,
  toColumnLabel,
  parseColumnLabel,
  toSref,
  toSrefs,
  parseRef,
  inRange,
  inRanges,
  isIntersectRanges,
  toRanges,
  toRefsFromRanges,
  toSrngFromRanges,
  parseRanges,
  mergeOverlapping,
  removeRange,
  isCrossSheetRef,
  parseCrossSheetRef,
  extractReferences,
  shiftSref,
  shiftFormula,
  shiftDimensionMap,
  shiftColumnLabel,
  shiftA1Range,
  remapIndex,
  moveRef,
  moveFormula,
  moveGrid,
  moveDimensionMap,
  moveColumnLabel,
  moveA1Range,
  relocateFormula,
  cloneConditionalFormatRule,
  normalizeConditionalFormatRule,
  normalizeConditionalFormatStyle,
  resolveConditionalFormatStyleAt,
  shiftConditionalFormatRules,
  moveConditionalFormatRules,
  CHECKBOX_TRUE,
  CHECKBOX_FALSE,
  cloneDataValidationRule,
  normalizeDataValidationRule,
  resolveDataValidationAt,
  isCheckboxChecked,
  toggleCheckboxValue,
  listOptionsOf,
  isValidListValue,
  isValidDateValue,
  isValidNumberValue,
  isValidTextValue,
  isValidValueForRule,
  describeDateRule,
  describeNumberRule,
  describeTextRule,
  normalizeListOptions,
  shiftDataValidationRules,
  moveDataValidationRules,
  validationOperandCount,
  cloneRangeStylePatch,
  normalizeRangeStylePatch,
  normalizeStylePatch,
  mergeStylePatch,
  pruneShadowedRangeStylePatches,
  shiftRangeStylePatches,
  moveRangeStylePatches,
  coalesceAdjacentRangeStylePatches,
  clipRangeStylePatches,
  translateRangeStylePatches,
  resolveRangeStyleAt,
  toMergeRange,
  isRefInMerge,
  shiftMerge,
  moveMerge,
  shiftMergeMap,
  moveMergeMap,
  isMergeSplitByMove,
  resolveSystemLocale,
  resolveCurrencyForLocale,
  buildLocaleFormatPreview,
  formatValue,
  inferInput,
  defaultAlign,
  getWorksheetCell,
  getWorksheetEntries,
  getWorksheetKeys,
  forEachWorksheetStoredCell,
  writeWorksheetCell,
  updateWorksheetCell,
  replaceWorksheetCells,
  resolveWorksheetCellStyle,
  safeWorksheetRecordKeys,
  safeWorksheetRecordEntries,
  safeWorksheetRecordValues,
  createWorksheetAxisId,
  createWorksheetCellKey,
  parseWorksheetCellKey,
  calculatePivot,
  materialize,
  parseSourceData,
  parseRange,
  DEFAULT_TAB_ID,
  DEFAULT_TAB_NAME,
  createWorksheet,
  createSpreadsheetDocument,
  initialSpreadsheetDocument,
  getPeerCursorColor,
  anchorToRef,
  refToAnchor,
  rangeAnchorToRange,
  rangeToRangeAnchor,
  createThread,
  addReply,
  cellAnchorToSref,
  isAnchorAlive,
  importXlsxFile,
  importXlsxWorkbook,
};

export type {
  LayoutRect,
  Store,
  Grid,
  Cell,
  CellStyle,
  ConditionalFormatOperator,
  ConditionalFormatRule,
  ConditionalFormatStyle,
  DataValidationKind,
  DataValidationRule,
  DataValidationOperator,
  BorderPreset,
  TextAlign,
  VerticalAlign,
  NumberFormat,
  FilterOperator,
  FilterCondition,
  FilterState,
  HiddenState,
  AggregateFunction,
  PivotFieldSort,
  PivotField,
  PivotValueField,
  PivotFilterField,
  PivotTableDefinition,
  PivotRecord,
  GroupNode,
  PivotCellType,
  PivotCell,
  PivotCellFormat,
  PivotResult,
  Ref,
  Sref,
  Range,
  Ranges,
  MergeSpan,
  Direction,
  Axis,
  SelectionType,
  GridResolver,
  RangeStylePatch,
  LocaleFormatPreview,
  FormatValueOptions,
  InferInputOptions,
  InferredInput,
  InferredInputFormat,
  Theme,
  ChartType,
  SheetChart,
  SheetImage,
  WorksheetFilterState,
  Worksheet,
  TabType,
  SheetKind,
  TabMeta,
  SpreadsheetDocument,
  CellAnchor,
  RangeAnchor,
  SelectionPresence,
  Comment,
  CommentAnchor,
  CommentAuthor,
  Thread,
  ImportedXlsxSheet,
  XlsxFileLike,
};

export {
  SHORTCUTS,
  formatCombo,
  type ShortcutEntry,
  type ShortcutCategory,
} from './view/shortcuts-catalog';
