import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { palette } from '../src/palette';
import { semantic } from '../src/semantic';
import { radius } from '../src/radius';
import { typography } from '../src/typography';

// Map of CSS variable name -> value, in deterministic emission order.
type Block = Array<[string, string]>;

function paletteBlock(mode: 'light' | 'dark'): Block {
  const n = mode === 'light' ? palette.neutrals.light : palette.neutrals.dark;
  const syrupForMode = mode === 'light' ? palette.syrup : palette.syrupBright;
  const berryForMode = mode === 'light' ? palette.berry : palette.berryBright;
  const leafForMode = mode === 'light' ? palette.leaf : palette.leafBright;
  return [
    ['--wb-bg', n.bg],
    ['--wb-paper', n.paper],
    ['--wb-ink', n.ink],
    ['--wb-sub', n.sub],
    ['--wb-rule', n.rule],
    ['--wb-syrup', syrupForMode],
    ['--wb-syrup-deep', mode === 'light' ? palette.syrupDeep : palette.butter],
    ['--wb-butter', palette.butter],
    ['--wb-berry', berryForMode],
    ['--wb-leaf', leafForMode],
  ];
}

function semanticBlock(mode: 'light' | 'dark'): Block {
  const m = semantic[mode];
  return [
    ['--background', m.background],
    ['--foreground', m.foreground],
    ['--card', m.card],
    ['--card-foreground', m.cardForeground],
    ['--popover', m.popover],
    ['--popover-foreground', m.popoverForeground],
    ['--primary', m.primary],
    ['--primary-foreground', m.primaryForeground],
    ['--secondary', m.secondary],
    ['--secondary-foreground', m.secondaryForeground],
    ['--muted', m.muted],
    ['--muted-foreground', m.mutedForeground],
    ['--accent', m.accent],
    ['--accent-foreground', m.accentForeground],
    ['--destructive', m.destructive],
    ['--border', m.border],
    ['--input', m.input],
    ['--ring', m.ring],
    ['--chart-1', m.chart1],
    ['--chart-2', m.chart2],
    ['--chart-3', m.chart3],
    ['--chart-4', m.chart4],
    ['--chart-5', m.chart5],
    ['--sidebar', m.sidebar],
    ['--sidebar-foreground', m.sidebarForeground],
    ['--sidebar-primary', m.sidebarPrimary],
    ['--sidebar-primary-foreground', m.sidebarPrimaryForeground],
    ['--sidebar-accent', m.sidebarAccent],
    ['--sidebar-accent-foreground', m.sidebarAccentForeground],
    ['--sidebar-border', m.sidebarBorder],
    ['--sidebar-ring', m.sidebarRing],
  ];
}

function rootOnlyBlock(): Block {
  return [
    ['--radius', radius.base],
    // Terminal palette is locked across both modes (matches existing index.css).
    ['--wb-terminal-bg', palette.terminal.bg],
    ['--wb-terminal-fg', palette.terminal.fg],
    // Font families — listed once, do not change between modes.
    ['--font-display', typography.display],
    ['--font-body', typography.body],
    ['--font-code', typography.code],
  ];
}

function format(block: Block, selector: string): string {
  const lines = block.map(([k, v]) => `  ${k}: ${v};`).join('\n');
  return `${selector} {\n${lines}\n}`;
}

export function renderTokensCss(): string {
  const lightVars = [
    ...rootOnlyBlock(),
    ...paletteBlock('light'),
    ...semanticBlock('light'),
  ];
  const darkVars = [...paletteBlock('dark'), ...semanticBlock('dark')];
  return [
    '/* AUTOGENERATED by packages/tokens/scripts/build-css.ts — do not edit. */',
    format(lightVars, ':root'),
    format(darkVars, '.dark'),
    '',
  ].join('\n\n');
}

const isMain = process.argv[1] === fileURLToPath(import.meta.url);
if (isMain) {
  const outPath = resolve(dirname(fileURLToPath(import.meta.url)), '../dist/tokens.css');
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, renderTokensCss(), 'utf8');
  console.log(`wrote ${outPath}`);
}
