import { extractReferences } from './formula/formula';
import {
  type Grid,
  type Cell,
  type CellStyle,
  type ConditionalFormatOperator,
  type ConditionalFormatRule,
  type ConditionalFormatStyle,
  type BorderPreset,
  type TextAlign,
  type VerticalAlign,
  type NumberFormat,
  type FilterOperator,
  type FilterCondition,
  type FilterState,
  type Ref,
  type Sref,
  type Range,
  type MergeSpan,
  type Direction,
  type Axis,
  type SelectionType,
  type GridResolver,
} from './model/types';
import {
  toSref,
  toSrefs,
  parseRef,
  inRange,
  isCrossSheetRef,
  parseCrossSheetRef,
} from './model/coordinates';
import {
  shiftSref,
  shiftFormula,
  shiftDimensionMap,
  remapIndex,
  moveRef,
  moveFormula,
  moveGrid,
  moveDimensionMap,
  relocateFormula,
} from './model/shifting';
import {
  cloneConditionalFormatRule,
  moveConditionalFormatRules,
  normalizeConditionalFormatRule,
  normalizeConditionalFormatStyle,
  resolveConditionalFormatStyleAt,
  shiftConditionalFormatRules,
} from './model/conditional-format';
import {
  type RangeStylePatch,
  cloneRangeStylePatch,
  normalizeRangeStylePatch,
  mergeStylePatch,
  normalizeStylePatch,
  pruneShadowedRangeStylePatches,
  shiftRangeStylePatches,
  moveRangeStylePatches,
  coalesceAdjacentRangeStylePatches,
  clipRangeStylePatches,
  translateRangeStylePatches,
  resolveRangeStyleAt,
} from './model/range-styles';
import {
  toMergeRange,
  isRefInMerge,
  shiftMerge,
  moveMerge,
  shiftMergeMap,
  moveMergeMap,
  isMergeSplitByMove,
} from './model/merging';
import { DimensionIndex } from './model/dimensions';
import { type Store } from './store/store';
import { CellIndex } from './store/cell-index';
import { findEdgeWithIndex } from './store/find-edge';
import { ReadOnlyStore } from './store/readonly';
import { initialize, Spreadsheet, type LayoutRect } from './view/spreadsheet';
import {
  buildLocaleFormatPreview,
  resolveCurrencyForLocale,
  resolveSystemLocale,
  type LocaleFormatPreview,
} from './model/locale';
import { type FormatValueOptions } from './model/format';
import {
  inferInput,
  type InferInputOptions,
  type InferredInput,
  type InferredInputFormat,
} from './model/input';

export {
  initialize,
  Spreadsheet,
  LayoutRect,
  Store,
  CellIndex,
  ReadOnlyStore,
  findEdgeWithIndex,
  Grid,
  Cell,
  CellStyle,
  ConditionalFormatOperator,
  ConditionalFormatRule,
  ConditionalFormatStyle,
  BorderPreset,
  TextAlign,
  VerticalAlign,
  NumberFormat,
  FilterOperator,
  FilterCondition,
  FilterState,
  Ref,
  Sref,
  Range,
  MergeSpan,
  Direction,
  Axis,
  SelectionType,
  GridResolver,
  DimensionIndex,
  toSref,
  toSrefs,
  parseRef,
  inRange,
  isCrossSheetRef,
  parseCrossSheetRef,
  extractReferences,
  shiftSref,
  shiftFormula,
  shiftDimensionMap,
  remapIndex,
  moveRef,
  moveFormula,
  moveGrid,
  moveDimensionMap,
  relocateFormula,
  cloneConditionalFormatRule,
  normalizeConditionalFormatRule,
  normalizeConditionalFormatStyle,
  resolveConditionalFormatStyleAt,
  shiftConditionalFormatRules,
  moveConditionalFormatRules,
  cloneRangeStylePatch,
  normalizeRangeStylePatch,
  normalizeStylePatch,
  mergeStylePatch,
  pruneShadowedRangeStylePatches,
  shiftRangeStylePatches,
  moveRangeStylePatches,
  coalesceAdjacentRangeStylePatches,
  clipRangeStylePatches,
  translateRangeStylePatches,
  resolveRangeStyleAt,
  type RangeStylePatch,
  toMergeRange,
  isRefInMerge,
  shiftMerge,
  moveMerge,
  shiftMergeMap,
  moveMergeMap,
  isMergeSplitByMove,
  resolveSystemLocale,
  resolveCurrencyForLocale,
  buildLocaleFormatPreview,
  type LocaleFormatPreview,
  type FormatValueOptions,
  inferInput,
  InferInputOptions,
  InferredInput,
  InferredInputFormat,
};
