/**
 * Tests for the CSS declaration scanner.
 *
 * Tested DIRECTLY rather than only through `cssVariables`, because this is the one
 * primitive 8b had to write from scratch — `design-editor-local-plugin.md` §4 calls the
 * default adapter "the only part of the token half with no reference implementation to
 * diff against". A bug here is silent: it produces a plausible stylesheet that has moved
 * the wrong bytes.
 *
 * The fixtures are real. `SHADCN` is shaped like what shadcn's CLI generates, and
 * `GENERATED` reproduces the banner-comment-then-`:root` shape of every generated
 * stylesheet — which is where the first version of `selectorList` actually failed.
 */

import { describe, expect, it } from 'vitest';
import {
  declMap,
  insertDecl,
  isSafeDeclarationValue,
  readDecls,
  removeDecl,
  selectorList,
  setDecl,
  topLevelBlocks,
} from '../../src/tokens/css-decls.ts';

const SHADCN = `@import "tailwindcss";
@custom-variant dark (&:is(.dark *));

:root {
  --radius: 0.625rem;
  --background: oklch(1 0 0);
  --primary: oklch(0.205 0 0);
  --font-sans: "Inter", sans-serif;
}

.dark {
  --background: oklch(0.145 0 0);
  --primary: oklch(0.922 0 0);
}

@theme inline {
  --color-primary: var(--primary);
}
`;

const GENERATED = `/* AUTOGENERATED by scripts/build-css.ts — do not edit. */

:root {
  --radius: 0.3rem;
}
.dark {
  --radius: 0.3rem;
}
`;

describe('topLevelBlocks', () => {
  it('finds rule blocks and at-rule blocks alike', () => {
    expect(topLevelBlocks(SHADCN).map((b) => b.selector.trim())).toEqual([
      ':root',
      '.dark',
      '@theme inline',
    ]);
  });

  it('does not treat a bodyless top-level statement as part of the next selector', () => {
    // Without the `depth === 0` semicolon reset, the leading `@import`/`@custom-variant`
    // lines glue onto `:root` and it never matches — so a stylesheet with imports (i.e.
    // every real one) would report no tokens at all.
    expect(topLevelBlocks(SHADCN)[0].selector.trim()).toBe(':root');
  });

  it('is blind to braces inside comments and strings', () => {
    const css = `/* } { */\n:root {\n  --a: "} {";\n}\n`;
    const blocks = topLevelBlocks(css);
    expect(blocks).toHaveLength(1);
    expect(declMap(readDecls(css, ':root'))).toEqual({ '--a': '"} {"' });
  });

  it('reports offsets that bracket the block exactly', () => {
    const css = ':root { --a: 1px; }';
    const [b] = topLevelBlocks(css);
    expect(css[b.open]).toBe('{');
    expect(css[b.close]).toBe('}');
  });
});

describe('selectorList', () => {
  it('strips a leading banner comment', () => {
    // THE BUG THIS FUNCTION EXISTS FOR. The scanner hands back everything between the
    // previous block and the `{`, so a generated stylesheet's banner arrives as part of
    // the first selector and `:root` fails to match — in the single most representative
    // fixture there is.
    const [first] = topLevelBlocks(GENERATED);
    expect(first.selector).toContain('AUTOGENERATED');
    expect(selectorList(first.selector)).toEqual([':root']);
  });

  it('splits a selector list', () => {
    expect(selectorList(':root, .light')).toEqual([':root', '.light']);
  });
});

describe('readDecls', () => {
  it('reads a generated stylesheet, banner and all', () => {
    expect(declMap(readDecls(GENERATED, ':root'))).toEqual({ '--radius': '0.3rem' });
    expect(declMap(readDecls(GENERATED, '.dark'))).toEqual({ '--radius': '0.3rem' });
  });

  it('matches a selector exactly, so a descendant rule is not the theme block', () => {
    // `.dark .note-preview` is in wafflebase's own `index.css`. A prefix test would read
    // a markdown-preview rule as the dark theme's tokens.
    const css = `.dark .note-preview {\n  --a: 1px;\n}\n.dark {\n  --b: 2px;\n}\n`;
    expect(declMap(readDecls(css, '.dark'))).toEqual({ '--b': '2px' });
  });

  it('matches a selector inside a list', () => {
    expect(declMap(readDecls(':root, .light { --a: 1px; }', ':root'))).toEqual({ '--a': '1px' });
  });

  it('keeps a value containing a semicolon, brace or quote intact', () => {
    const css = `:root {\n  --a: "semi; colon { brace }";\n  --b: 2px;\n}\n`;
    expect(declMap(readDecls(css, ':root'))).toEqual({
      '--a': '"semi; colon { brace }"',
      '--b': '2px',
    });
  });

  it('keeps a value containing a colon inside a function', () => {
    // The colon scan is paren-depth aware. A naive first-`indexOf(':')` on the value side
    // would re-split this declaration.
    const css = `:root {\n  --a: url("data:image/svg+xml,x");\n}\n`;
    expect(declMap(readDecls(css, ':root'))).toEqual({ '--a': 'url("data:image/svg+xml,x")' });
  });

  it('reads the last declaration when it has no trailing semicolon', () => {
    expect(declMap(readDecls(':root {\n  --a: 1px\n}', ':root'))).toEqual({ '--a': '1px' });
  });

  it('reads a declaration that FOLLOWS a comment', () => {
    // THE BUG A WEAKER TEST HID. A pending declaration's span begins right after the
    // previous `;`, so a grouping comment between the two lands inside it, becomes part of
    // the property name, and the declaration is dropped as non-custom-property — invisible
    // to the editor and unwritable. `/* Brand */` group headers are entirely ordinary in a
    // hand-authored stylesheet, so this is the common case, not an edge one.
    const css = ':root {\n  --a: 1px;\n  /* Brand */\n  --b: 2px;\n}\n';
    expect(declMap(readDecls(css, ':root'))).toEqual({ '--a': '1px', '--b': '2px' });
  });

  it('reads the FIRST declaration when a comment precedes it', () => {
    const css = ':root {\n  /* Brand */\n  --a: 1px;\n}\n';
    expect(declMap(readDecls(css, ':root'))).toEqual({ '--a': '1px' });
  });

  it('reads a declaration wrapped in comments on both sides', () => {
    const css = ':root {\n  /* a */ --a: 1px; /* b */\n  --c: 2px;\n}\n';
    expect(declMap(readDecls(css, ':root'))).toEqual({ '--a': '1px', '--c': '2px' });
  });

  it('survives an unterminated comment without swallowing the block', () => {
    const css = ':root {\n  --a: 1px;\n  /* never closed\n';
    expect(declMap(readDecls(css, ':root'))).toEqual({});
  });

  it('leaves a preceding comment in place when a declaration is removed', () => {
    // The comment is the author's, not ours to delete: the removal walks back only over
    // whitespace.
    const css = ':root {\n  /* Brand */\n  --a: 1px;\n  --b: 2px;\n}\n';
    expect(removeDecl(css, ':root', '--a').text).toBe(':root {\n  /* Brand */\n  --b: 2px;\n}\n');
  });

  it('skips a non-custom property', () => {
    // The editor has no vocabulary for `color: red`, and rewriting one would be outside
    // anything the user asked for.
    expect(declMap(readDecls(':root {\n  color: red;\n  --a: 1px;\n}', ':root'))).toEqual({
      '--a': '1px',
    });
  });

  it('does NOT see a block nested inside an at-rule — a documented limit', () => {
    // A `@media (prefers-color-scheme: dark)` project reads as having no dark theme
    // rather than as having a wrong one. Asserted so the limit is a decision on record,
    // not an accident that a later change can quietly reverse.
    const css = `@media (prefers-color-scheme: dark) {\n  :root { --a: 1px; }\n}\n`;
    expect(readDecls(css, ':root')).toEqual([]);
  });

  it('returns duplicates rather than merging them', () => {
    const css = ':root { --a: 1px; }\n:root { --a: 5px; }\n';
    expect(readDecls(css, ':root').map((d) => d.value)).toEqual(['1px', '5px']);
  });

  it('excludes a TRAILING comment from the value', () => {
    // Otherwise the editor displays `1px /* note */` as the value, and `setDecl` — which
    // splices the value span — deletes the author's comment as a side effect of an edit.
    expect(declMap(readDecls(':root {\n  --a: 1px /* note */;\n}\n', ':root'))).toEqual({
      '--a': '1px',
    });
  });

  it('keeps a comment that sits BETWEEN two parts of a value', () => {
    // CSS treats a comment as whitespace, so this is a two-part value. Cutting at the
    // first comment would silently drop `solid`.
    expect(declMap(readDecls(':root {\n  --a: 1px /* c */ solid;\n}\n', ':root'))).toEqual({
      '--a': '1px /* c */ solid',
    });
  });

  it('reports value offsets that slice out exactly the value', () => {
    const css = `:root {\n  --font: "Inter", sans-serif;\n}\n`;
    const [d] = readDecls(css, ':root');
    expect(css.slice(d.valueStart, d.valueEnd)).toBe(d.value);
  });

  it('reports exact offsets for EVERY declaration in a block, not just the first', () => {
    // The offsets are derived from each declaration's own start. An earlier version
    // computed them by walking back from the NEXT declaration's start, which is correct
    // only incidentally and is the kind of arithmetic that breaks silently.
    for (const d of readDecls(SHADCN, ':root')) {
      expect(SHADCN.slice(d.valueStart, d.valueEnd)).toBe(d.value);
      expect(SHADCN.slice(d.start, d.end)).toContain(`${d.prop}:`);
      expect(SHADCN[d.end]).toBe(';');
    }
  });
});

describe('declMap', () => {
  it('folds duplicates last-wins, which is the cascade', () => {
    // First-wins would show the editor a value the page is not displaying.
    expect(declMap(readDecls(':root { --a: 1px; }\n:root { --a: 5px; }', ':root'))).toEqual({
      '--a': '5px',
    });
  });
});

describe('setDecl', () => {
  it('replaces only the value bytes', () => {
    const r = setDecl(SHADCN, ':root', '--primary', 'red');
    expect(r.located).toBe(true);
    // `oklch(0.205 0 0)` is 16 characters, `red` is 3 — so an exact value splice moves
    // exactly -13 bytes and touches nothing else.
    expect(r.text.length - SHADCN.length).toBe(-13);
    expect(r.text).toContain('  --primary: red;');
    expect(r.text.replace('  --primary: red;', '  --primary: oklch(0.205 0 0);')).toBe(SHADCN);
  });

  it('edits the requested theme block only', () => {
    const r = setDecl(SHADCN, '.dark', '--primary', 'red');
    expect(declMap(readDecls(r.text, '.dark'))['--primary']).toBe('red');
    expect(declMap(readDecls(r.text, ':root'))['--primary']).toBe('oklch(0.205 0 0)');
  });

  it('targets the LAST duplicate, which is the one in effect', () => {
    // Writing the first would be overridden by the later duplicate: the write lands, the
    // diff looks right, and the page does not change.
    const css = ':root { --a: 1px; }\n:root { --a: 5px; }\n';
    const r = setDecl(css, ':root', '--a', '9px');
    expect(declMap(readDecls(r.text, ':root'))).toEqual({ '--a': '9px' });
    expect(r.text).toBe(':root { --a: 1px; }\n:root { --a: 9px; }\n');
  });

  it('refuses an undeclared property rather than creating it', () => {
    const r = setDecl(SHADCN, ':root', '--nope', 'red');
    expect(r.located).toBe(false);
    expect(r.reason).toContain('not declared');
    expect(r.text).toBe(SHADCN);
  });

  it('preserves a trailing comment when the value changes', () => {
    expect(setDecl(':root {\n  --a: 1px /* note */;\n}\n', ':root', '--a', 'red').text).toBe(
      ':root {\n  --a: red /* note */;\n}\n',
    );
  });

  it('refuses a missing block', () => {
    expect(setDecl(SHADCN, '.nope', '--primary', 'red').located).toBe(false);
  });
});

describe('insertDecl', () => {
  it('appends before the closing brace', () => {
    const r = insertDecl(SHADCN, ':root', '--brand', '#fff');
    expect(r.located).toBe(true);
    expect(declMap(readDecls(r.text, ':root'))['--brand']).toBe('#fff');
    expect(r.text).toContain('  --font-sans: "Inter", sans-serif;\n  --brand: #fff;\n}');
  });

  it('matches the block\'s own indentation instead of assuming two spaces', () => {
    expect(insertDecl(':root {\n\t--a: 1px;\n}\n', ':root', '--b', '2px').text).toBe(
      ':root {\n\t--a: 1px;\n\t--b: 2px;\n}\n',
    );
  });

  it('preserves CRLF line endings', () => {
    expect(insertDecl(':root {\r\n  --a: 1px;\r\n}\r\n', ':root', '--b', '2px').text).toBe(
      ':root {\r\n  --a: 1px;\r\n  --b: 2px;\r\n}\r\n',
    );
  });

  it('handles an empty block', () => {
    expect(insertDecl(':root {\n}\n', ':root', '--b', '2px').text).toBe(
      ':root {\n  --b: 2px;\n}\n',
    );
  });

  it('indents correctly in a block whose last declaration follows a comment', () => {
    const css = ':root {\n  --a: 1px;\n  /* -- note */\n  --b: 2px;\n}\n';
    expect(insertDecl(css, ':root', '--c', '3px').text).toBe(
      ':root {\n  --a: 1px;\n  /* -- note */\n  --b: 2px;\n  --c: 3px;\n}\n',
    );
  });

  it('falls back to a default indent when the last declaration shares its line', () => {
    // Copying the prefix would put `--a: 1px;` in front of the inserted declaration.
    expect(insertDecl(':root {\n  --a: 1px; --b: 2px;\n}\n', ':root', '--c', '3px').text).toBe(
      ':root {\n  --a: 1px; --b: 2px;\n  --c: 3px;\n}\n',
    );
  });

  it('refuses a duplicate rather than declaring the property twice', () => {
    const r = insertDecl(SHADCN, ':root', '--primary', '#fff');
    expect(r.located).toBe(false);
    expect(r.reason).toContain('already declared');
    expect(r.text).toBe(SHADCN);
  });

  it('appends to the LAST matching block', () => {
    const css = ':root {\n  --a: 1px;\n}\n:root {\n  --b: 2px;\n}\n';
    expect(insertDecl(css, ':root', '--c', '3px').text).toBe(
      ':root {\n  --a: 1px;\n}\n:root {\n  --b: 2px;\n  --c: 3px;\n}\n',
    );
  });

  it('refuses a duplicate declared in an EARLIER block', () => {
    // Checking only the target block let this add a second `--a`, so the file declared the
    // property twice — the state `setDecl`'s last-wins targeting exists to cope with, now
    // created by the editor itself.
    const css = ':root {\n  --a: 1px;\n}\n:root {\n  --b: 2px;\n}\n';
    const r = insertDecl(css, ':root', '--a', '9px');
    expect(r.located).toBe(false);
    expect(r.reason).toContain('already declared');
    expect(r.text).toBe(css);
  });

  it('inserts INSIDE a one-line block', () => {
    // The walk-back for "the closing brace's line" finds no newline here, so it landed at
    // offset 0 and spliced the declaration in front of the selector:
    // `"  --b: 2px;\n:root { --a: 1px; }"` — broken CSS that `readDecls` could not see.
    const r = insertDecl(':root { --a: 1px; }', ':root', '--b', '2px');
    expect(r.text).toBe(':root { --a: 1px; --b: 2px; }');
    expect(declMap(readDecls(r.text, ':root'))).toEqual({ '--a': '1px', '--b': '2px' });
  });

  it('inserts into an empty one-line block', () => {
    expect(insertDecl(':root {}', ':root', '--a', '1px').text).toBe(':root { --a: 1px; }');
    expect(insertDecl(':root { }', ':root', '--a', '1px').text).toBe(':root { --a: 1px; }');
  });

  it('round-trips insert → remove on a one-line block', () => {
    const css = ':root { --a: 1px; }';
    const added = insertDecl(css, ':root', '--b', '2px');
    expect(removeDecl(added.text, ':root', '--b').text).toBe(css);
  });

  it('reports a missing block', () => {
    const r = insertDecl(SHADCN, '.nope', '--a', '1px');
    expect(r.located).toBe(false);
    expect(r.reason).toContain('no .nope block');
  });
});

describe('removeDecl', () => {
  it('removes the whole line, leaving no blank', () => {
    const r = removeDecl(SHADCN, ':root', '--primary');
    expect(r.located).toBe(true);
    expect(r.text).toContain('  --background: oklch(1 0 0);\n  --font-sans:');
    expect(declMap(readDecls(r.text, ':root'))['--primary']).toBeUndefined();
    // The dark override is a separate declaration and is NOT collateral.
    expect(declMap(readDecls(r.text, '.dark'))['--primary']).toBe('oklch(0.922 0 0)');
  });

  it('round-trips with insertDecl', () => {
    const added = insertDecl(SHADCN, ':root', '--brand', '#fff');
    expect(removeDecl(added.text, ':root', '--brand').text).toBe(SHADCN);
  });

  it('removes every duplicate, not just the last', () => {
    // Leaving an earlier duplicate would look like the removal had failed, because the
    // property would still resolve.
    const css = ':root {\n  --a: 1px;\n}\n:root {\n  --a: 5px;\n}\n';
    const r = removeDecl(css, ':root', '--a');
    expect(readDecls(r.text, ':root')).toEqual([]);
    expect(r.text).toBe(':root {\n}\n:root {\n}\n');
  });

  it('removes a final declaration that has no trailing semicolon', () => {
    expect(removeDecl(':root {\n  --a: 1px\n}\n', ':root', '--a').text).toBe(':root {\n}\n');
  });

  it('does not eat the selector when the declaration shares its line', () => {
    // Walking back to the line start is only safe over whitespace. On a one-line block it
    // reaches `:root { ` and would delete the selector and brace with it, leaving
    // unparseable CSS.
    expect(removeDecl(':root { --a: 1px; }', ':root', '--a').text).toBe(':root { }');
  });

  it('does not eat a same-line comment or a preceding declaration', () => {
    expect(removeDecl(':root {\n  /* a */ --a: 1px;\n}\n', ':root', '--a').text).toBe(
      ':root {\n  /* a */ \n}\n',
    );
    expect(removeDecl(':root {\n  --a: 1px; --b: 2px;\n}\n', ':root', '--b').text).toBe(
      ':root {\n  --a: 1px; \n}\n',
    );
  });

  it('refuses an absent property', () => {
    const r = removeDecl(SHADCN, ':root', '--nope');
    expect(r.located).toBe(false);
    expect(r.text).toBe(SHADCN);
  });
});

describe('isSafeDeclarationValue', () => {
  const ACCEPTED = [
    'oklch(0.7 0.1 250)',
    '#B8651A',
    '0.625rem',
    '"Inter", sans-serif',
    'calc(var(--radius) - 4px)',
    'color-mix(in oklab, var(--x) 50%, #fff)',
    // A semicolon and braces INSIDE a function or a string are ordinary CSS. Rejecting
    // these is the failure mode a naive character blocklist would have.
    'url("data:image/svg+xml;base64,AAAA")',
    "'a; b { c }'",
    'var(--a, var(--b, 1px))',
  ];

  for (const v of ACCEPTED) {
    it(`accepts ${v}`, () => {
      expect(isSafeDeclarationValue(v)).toBe(true);
    });
  }

  const REFUSED: [string, string][] = [
    ['red; } body { display: none } :root { --x:', 'would end the declaration'],
    ['red;', 'would end the declaration'],
    ['red }', 'would end the declaration'],
    ['red {', 'would end the declaration'],
    ['red /* unterminated', 'unterminated comment'],
    ['"unterminated', 'unterminated string'],
    ['calc(1px', 'unbalanced parentheses'],
    ['calc(1px))', 'unbalanced parentheses'],
  ];

  for (const [v, reason] of REFUSED) {
    it(`refuses ${JSON.stringify(v)}`, () => {
      const r = isSafeDeclarationValue(v);
      expect(r).not.toBe(true);
      expect(String(r)).toContain(reason);
    });
  }
});
